### ISSUE TITLE
Error  

### ISSUE THREAD

**Issue by dafahan** [nxvvvv/safe-exam-browser-bypass#11]
<img width="595" alt="image" src="https://github.com/nxvvvv/safe-exam-browser-bypass/assets/74886281/63bae901-7171-4a95-be6e-d8aa4d713c60">

**Comment by nxvvvv** [comment]
Could you please provide the logs, or alternatively, could you explain when this occurred? Also, ensure that you have copied and replaced all three files in the software folder.

**Comment by dafahan** [comment]
> Could you please provide the logs, or alternatively, could you explain when this occurred? Also, ensure that you have copied and replaced all three files in the software folder.

Yes, I have replaced those three files , this happened when I opened the application

**Comment by No-Biggie805** [comment]
To solve you need v3.5 of SEB, not 3.6.
