### ISSUE TITLE
Fair use disclaimer maybe?

### ISSUE THREAD

**Issue by lathianamc** [nxvvvv/safe-exam-browser-bypass#15]
@nxvvvv again, thanks for all your effort!

I was thinking, as an academic myself and as a person with a poor memory but a very high understanding of various disciplines, maybe you should consider including in your Readme file a disclaimer for this project. You see, most people will use this to cheat on the exam, I know it, you know it, everybody knows it. But, cheating in an exam isn't fair and frankly speaking, isn’t beneficial for the one who cheats in the first place, since the whole point is to learn.

The reason I'm interested in this project is because I don't indulge in the method of examining the memory capacity of a person, but rather his understanding of the discipline he studies. When I issue an exam to my students, I always encourage them to bring their notes with them, none of my assignments will be directly answered from their class notes if they have not got an understanding of the matter. Exams must prioritise the student's ability to be able to know his tools and how to use them. Bring a surgeon without his instruments to a surgery table, he won't be able to perform, bring a lawyer to write you a report of a case without him having access to data not only for the case but to the law itself, and he might produce a report, average at best, due-to that a) you can't memorise all (Mike Ross does not exist) and b) there is absolutely no need to memorise all, except if you plan to work in a cave with zero access to info.

Therefore, I would suggest you add a small disclaimer indicating that the purpose of this project is not to indulge in cheating but to allow people who struggle with their memory ability. And yeah, I know that this is debatable and now there is GPT and cheating will be there, but, guess what, it was always there, and will be. Having that disclaimer, it might at least protect somehow the repository from being taken down.

That's just my theory, cheers!

**Comment by nxvvvv** [comment]
Thank you. I updated the same in latest [patch](https://github.com/nxvvvv/safe-exam-browser-bypass/commit/6898b6f923d41a46197876242e3badbbb5d6b73e)

Even though what I've written is ironic, it works :D
