### ISSUE TITLE
Some questions about SEB Pass

### ISSUE THREAD

**Issue by DeaoZhang** [nxvvvv/safe-exam-browser-bypass#18]
Hello,
I would like to ask, if I am using SEB alliance edition, how can I solve the problem that I can't create a session when I open seb?

**Comment by nxvvvv** [comment]
Hey, Normal SEB DLLs won't work with the Alliance version and don't worry I'm working on the Alliance version. I'll provide the files in the releases shortly.

**Comment by DeaoZhang** [comment]
Please provide the new file as soon as possible, it will help me a lot thanks!

**Comment by nxvvvv** [comment]
Here you go: https://github.com/nxvvvv/safe-exam-browser-bypass/releases/download/v3.6.0.633/SEB.Alliance.v3.6.0.40.Bypass.zip

**Comment by DeaoZhang** [comment]
How do I use it?

**Comment by nxvvvv** [comment]
- I presume you have SEB Alliance installed within a VM.
- Download and extract the provided zip.
- Copy the three extracted files.
- Press the Windows button, type "Safe Exam Browser (Alliance Version)," and it will appear enlarged on the right side of the search.
- Choose "Open file location" on the right side.
- If encountering a shortcut file, right-click and select "Open file location" again.
- In the main folder, paste the copied contents.
- Confirm the replacement for each file.
- Done
