### ISSUE TITLE
Interested

### ISSUE THREAD

**Issue by Scrut1ny** [nxvvvv/safe-exam-browser-bypass#24]
I noticed you've recently updated your bypass for SEB, I'm currently working on my own VM bypass for Virtual Box, VMware, and QEMU. I'm trying to bypass Anti Cheats in games and Proctors. I was wandering on how much knowledge you have on all of this stuff and if you could assist me in making a undetectable setup. Hmu on Discord if you wanna chat - 0x115#2564

My personal project: https://github.com/Scrut1ny/VM-Undetected

**Comment by nxvvvv** [comment]
Hey there!

Sorry for the late reply. I've been busy with my college and internships.

And YES! I'm interested in collaborating with you for hardening the VM. I've also integrated a few patches in the new update(into the VM) which contains pretty heavy stuff which almost bypasses the VM detection.

I'll release it ASAP, so yea look out for the release
