### ISSUE TITLE
Can we collaborate 

### ISSUE THREAD

**Issue by developerfromEarth** [nxvvvv/safe-exam-browser-bypass#27]
Hey can we sell this software please.
We can work together to earn from this. I have experience in this. SO Please we can collaborate

**Comment by 0xnecromancer** [comment]
Sounds like a great idea!
Just make sure you are ready for that lawsuit 😄

**Comment by nxvvvv** [comment]
> Hey can we sell this software please.
> We can work together to earn from this. I have experience in this. SO Please we can collaborate 

Well nope. I'm only interested in sharing not selling so yea
