### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by FlatBanana** [nxvvvv/safe-exam-browser-bypass#28]
Hi
I am a Student and trying to edit the Code from the SEB github repo to achieve a similar thing. But when trying to compile seb-win-refactoring/SafeExamBrowser.SystemComponents i am getting an error that the NAudio library could not be found. I am very new to C# so i don't really know what i am doing. Would you mind sharing your "process of compiling".  That would really help me out.
Thanks in advance
Have a nice Day!

**Comment by rezinch** [comment]
I used dnspy to rewrite it and it worked for me 
if u want I can help u hmu on telegram
@WR3_NCH

**Comment by nxvvvv** [comment]
> Hi
> I am a Student and trying to edit the Code from the SEB github repo to achieve a similar thing. But when trying to compile seb-win-refactoring/SafeExamBrowser.SystemComponents i am getting an error that the NAudio library could not be found. I am very new to C# so i don't really know what i am doing. Would you mind sharing your "process of compiling".  That would really help me out.
> Thanks in advance
> Have a nice Day!

Well you don't compile the entire thing, you just edit and compile the executables or libraries. 

Install SEB on your system, get a .NET reverse engineering tool(I'd recommend dnspyEx) and then go to the installation folder, patch it up and compile it.
