### ISSUE TITLE
unsafeexambrowser

### ISSUE THREAD

**Issue by quintenvandamme** [nxvvvv/safe-exam-browser-bypass#46]
I have made my own bypass version from scratch 2 years ago and have since released a 2.0 that has some nice features. Its also super easy to install thanks to its installer. You can even override safeexambrowser so it starts unsafeexambrowser. And the best feature you can multitask with all apps as it it was meant to be.
![image](https://github.com/user-attachments/assets/bb1ec0cd-5dbe-4621-96a5-24d86a3d3feb)

Let me know if i should bring some of those features to your project. You can check it out [here](https://github.com/quintenvandamme/unsafeexambrowser)

**Comment by luciohumberto** [comment]
preciso urgentemente da sua ajuda, instalei o unsafeexambrowser e vou realizar o teste anpad, aí clico no arquivo que redireciona e ele só abre com o safeexambrowser ja tentei de todo jeito mudar mas nao consegui, vou fazer a prova no domingo e preciso de uma solucao para isso ate sexta, para poder me familiarizar melhor

**Comment by nxvvvv** [comment]
Hey, I've been working on mine for a while and yea, it is **UNSAFE** to use patched exam browser, which, I'll be updating in a while which involves no patching or replacing files of the SEB so that the integrity checks passes. So yea, good initiative but won't work. Sorry

**Comment by luciohumberto** [comment]
Ok... Thanos..

Em qua., 20 de nov. de 2024 18:28, nav ***@***.***> escreveu:

**Comment by luciohumberto** [comment]
Ok..... Thank you

Em qui., 21 de nov. de 2024 12:57, Lucio Humberto ***@***.***>
escreveu:

**Comment by luciohumberto** [comment]
And do you know when your new project will be ready? And can you let
me know when it's ready, via email at ***@***.*** please?
thanks

Lúcio Humberto Silva


Em qua., 20 de nov. de 2024 às 18:28, nav ***@***.***>
escreveu:
