### ISSUE TITLE
[REQ] Support for v3.6

### ISSUE THREAD

**Issue by lathianamc** [nxvvvv/safe-exam-browser-bypass#8]
Hey! Thanks for all your work!

Version 3.6 is out, it would be great to support it.

Thanks!

**Comment by nxvvvv** [comment]
Currently working on a few other projects. I will surely start working on it :)

**Comment by lathianamc** [comment]
I think most people have their semester exams starting by the end of January, it would be great if we could have v3.6 by that time :)


PS: I saw another user asking about backing monetarily your project, I would recommend you have a way for people to donate money to you. Because you have done remarkable work so far, I see absolutely no reason for not kindly asking for a donation.

**Comment by nxvvvv** [comment]
@lathianamc Hey, I updated the donation link. Now everyone can donate on github by clicking the support button.
