### ISSUE TITLE
SEB server

### ISSUE THREAD

**Issue by Paweljavelin** [nxvvvv/safe-exam-browser-bypass#9]
My uni is using SEB server which can pull logs all the time. Is there any way for me to prevent them for finding out im using SEB vm bypass?

**Comment by nxvvvv** [comment]
I think the logs are fine for now, but I'll tweak the logging script to get the logs we actually need.

**Comment by lathianamc** [comment]
@Paweljavelin my Uni also uses a private SEB server, and I'm kind of sure that they could catch me if they dig into their logs deep. I do feel that this should be addressed as per @nxvvvv suggestion, but, frankly speaking, I'll be very surprised if they would sit and read the logs for hundreds of students :P I mean, is there a chance to be caught? Yes. Is there a high probability? No. Worst case scenario they can't prove it, you explain to them that you are not tech-savvy and you have no clue what the accusations are, and most likely you'll have to retake the exam :P

**Comment by nxvvvv** [comment]
I've updated SEB patch to 3.6.633. I think this should resolve the logs. Tried to make it as perfect as possible.
